version: "3"
services:
  first-node:
    image: node
    command: java -jar /node/build/libs/SmallBlockchain-1.0-SNAPSHOT.jar
    ports:
      - "11116:11116"
    environment:
      - port=11116
      - other=11117,11118
      - generated=false
  second-node:
    image: node
    command: java -jar /node/build/libs/SmallBlockchain-1.0-SNAPSHOT.jar
    ports:
      - "11117:11117"
    environment:
      - port=11117
      - other=11116,11118
      - generated=false
  third-node:
    image: node
    command: java -jar /node/build/libs/SmallBlockchain-1.0-SNAPSHOT.jar
    ports:
      - "11118:11118"
    environment:
      - port=11118
      - other=11116,11117
      - generated=true